use serde::Deserialize;

#[derive(sqlx::FromRow, Deserialize, Debug, Default)]
#[allow(unused)]
pub struct Level {
    pub game_version: i32,
    pub binary_version: i32,
    pub username: String,
    pub level_id: i32,
    pub level_name: String,
    pub level_desc: String,
    pub level_version: i32,
    pub level_length: i32,
    pub audio_track: i32,
    pub auto: i32,
    pub password: i32,
    pub original: i32,
    pub two_player: i32,
    pub song_id: i32,
    pub song_ids: Option<String>,
    pub sfx_ids: Option<String>,
    pub objects: i32,
    pub coins: i32,
    pub requested_stars: i32,
    pub extra_string: String,
    pub level_string: Option<String>,
    pub level_info: String,
    pub secret: String,
    pub star_difficulty: i32,
    pub downloads: i32,
    pub likes: i32,
    pub star_demon: i32,
    pub star_auto: i16,
    pub star_stars: i32,
    pub upload_date: i64,
    pub update_date: i64,
    pub rate_date: i64,
    pub star_coins: i32,
    pub star_featured: i32,
    pub star_hall: i32,
    pub star_epic: i32,
    pub star_demon_diff: i32,
    pub user_id: i32,
    pub ext_id: String,
    pub unlisted: i32,
    pub original_reup: i32,
    pub hostname: String,
    pub is_cp_shared: i32,
    pub is_deleted: i32,
    pub is_ldm: i32,
    pub unlisted2: i32,
    pub wt: i32,
    pub wt2: i32,
    pub ts: i32,
    pub settings_string: String,
}

#[derive(sqlx::FromRow, Deserialize, Debug, Default)]
#[allow(unused)]
pub struct User {
    pub is_registered: i32,
    pub user_id: i32,
    pub ext_id: String,
    pub username: String,
    pub stars: i32,
    pub demons: i32,
    pub icon: i32,
    pub color1: i32,
    pub color2: i32,
    pub color3: i32,
    pub icon_type: i32,
    pub coins: i32,
    pub user_coins: i32,
    pub special: i32,
    pub game_version: i32,
    pub secret: String,
    pub acc_icon: i32,
    pub acc_ship: i32,
    pub acc_ball: i32,
    pub acc_bird: i32,
    pub acc_dart: i32,
    pub acc_robot: Option<i32>,
    pub acc_glow: i32,
    pub acc_swing: i32,
    pub acc_jetpack: i32,
    pub dinfo: Option<String>,
    pub sinfo: Option<String>,
    pub pinfo: Option<String>,
    pub creator_points: f64,
    pub ip: String,
    pub last_played: i32,
    pub diamonds: i32,
    pub moons: i32,
    pub orbs: i32,
    pub completed_lvls: i32,
    pub acc_spider: i32,
    pub acc_explosion: i32,
    pub chest1_time: i32,
    pub chest2_time: i32,
    pub chest1_count: i32,
    pub chest2_count: i32,
    pub is_banned: i32,
    pub is_creator_banned: i32,
}

#[derive(sqlx::FromRow, Deserialize, Debug, Default)]
#[allow(unused)]
pub struct Account {
    pub username: String,
    pub password: String,
    pub gjp2: Option<String>,
    pub email: String,
    pub account_id: i32,
    pub is_admin: i32,
    pub ms: i32,
    pub fr_s: i32,
    pub cs: i32,
    pub youtube_url: String,
    pub twitter: String,
    pub twitch: String,
    pub salt: String,
    pub register_date: i32,
    pub friends_count: i32,
    pub discord_id: i64,
    pub discord_link_req: i64,
    pub is_active: bool,
}

#[derive(sqlx::FromRow, Deserialize, Debug, Default)]
#[allow(unused)]
pub struct Role {
    pub role_id: i64,
    pub priority: i32,
    pub role_name: String,
    pub command_rate: i32,
    pub command_feature: i32,
    pub command_epic: i32,
    pub command_unepic: i32,
    pub command_verifycoins: i32,
    pub command_daily: i32,
    pub command_weekly: i32,
    pub command_delete: i32,
    pub command_setacc: i32,
    pub command_rename_own: i32,
    pub command_rename_all: i32,
    pub command_pass_own: i32,
    pub command_pass_all: i32,
    pub command_description_own: i32,
    pub command_description_all: i32,
    pub command_public_own: i32,
    pub command_public_all: i32,
    pub command_unlist_own: i32,
    pub command_unlist_all: i32,
    pub command_sharecp_own: i32,
    pub command_sharecp_all: i32,
    pub command_song_own: i32,
    pub command_song_all: i32,
    pub profilecommand_discord: i32,
    pub action_rate_demon: i32,
    pub action_rate_stars: i32,
    pub action_rate_difficulty: i32,
    pub action_request_mod: i32,
    pub action_suggest_rating: i32,
    pub action_delete_comment: i32,
    pub tool_leaderboardsban: i32,
    pub tool_packcreate: i32,
    pub tool_quests_create: i32,
    pub tool_modactions: i32,
    pub tool_suggestlist: i32,
    pub dashboard_mod_tools: i32,
    pub modip_category: i32,
    pub is_default: i32,
    pub comment_color: String,
    pub mod_badge_level: i32,
}

#[derive(sqlx::FromRow, Deserialize, Debug, Default)]
#[allow(unused)]
pub struct LevelScore {
    pub score_id: i32,
    pub account_id: i32,
    pub level_id: i32,
    pub percent: i32,
    pub upload_date: i32,
    pub attempts: i32,
    pub coins: i32,
    pub clicks: i32,
    pub time: i32,
    pub progresses: String,
    pub daily_id: i32,
}

#[derive(sqlx::FromRow, Deserialize, Debug, Default)]
#[allow(unused)]
pub struct FriendRequest {
    pub account_id: i32,
    pub to_account_id: i32,
    pub comment: String,
    pub upload_date: i32,
    pub id: i32,
    pub is_new: bool,
}

#[derive(sqlx::FromRow, Deserialize, Debug, Default)]
#[allow(unused)]
pub struct Message {
    pub user_id: i32,
    pub username: String,
    pub body: String,
    pub subject: String,
    pub acc_id: i32,
    pub message_id: i32,
    pub to_account_id: i32,
    pub timestamp: i32,
    pub secret: String,
    pub is_new: i32,
}
